import type { PatchmillTriageStateMap } from "../../../policy/triage-state.ts";
import type { IssueSummary } from "./types.ts";

export const TRIAGE_COMMENT_PREFIX =
  "> _This was generated by AI during triage._";
export const MAX_BLOCKER_ISSUES = 20;

type BlockerHost = {
  viewIssue(issueNumber: number): Promise<IssueSummary>;
};

export type BlockedIssueResolution =
  | { status: "missing-blockers"; blockedBy: number[]; openBlockers: number[] }
  | { status: "still-blocked"; blockedBy: number[]; openBlockers: number[] }
  | { status: "unblocked"; blockedBy: number[]; openBlockers: number[] };

function issueRefs(issueNumbers: readonly number[]): string {
  return issueNumbers.map((issueNumber) => `#${issueNumber}`).join(", ");
}

function uniqueIssueNumbers(issueNumbers: readonly number[]): number[] {
  return [...new Set(issueNumbers)].sort((left, right) => left - right);
}

export function createBlockedComment(
  blockedBy: readonly number[],
  rationale: string,
): string {
  return [
    TRIAGE_COMMENT_PREFIX,
    "",
    `Blocked by: ${issueRefs(uniqueIssueNumbers(blockedBy))}`,
    "",
    rationale.trim(),
  ].join("\n");
}

export function createUnblockedComment(blockedBy: readonly number[]): string {
  return [
    TRIAGE_COMMENT_PREFIX,
    "",
    `The blocking issues are now closed: ${issueRefs(uniqueIssueNumbers(blockedBy))}.`,
    "",
    "This issue is now agent-ready.",
  ].join("\n");
}

function trustedAuthorSet(trustedAuthors: readonly string[]): Set<string> {
  return new Set(
    trustedAuthors.map((author) => author.trim()).filter((author) => author),
  );
}

function blockedByFromComment(comment: string): number[] {
  if (!comment.includes(TRIAGE_COMMENT_PREFIX)) return [];
  const blockedLine = comment
    .split(/\r?\n/u)
    .map((line) => line.trim())
    .find((line) => /^Blocked by:/iu.test(line));
  if (!blockedLine) return [];
  return uniqueIssueNumbers(
    [...blockedLine.matchAll(/#([1-9]\d*)/gu)].map((match) => Number(match[1])),
  );
}

export function blockedByFromIssue(
  issue: Pick<IssueSummary, "comments">,
  trustedAuthors: readonly string[],
): number[] {
  const trusted = trustedAuthorSet(trustedAuthors);
  if (trusted.size === 0) return [];
  const comments = [...(issue.comments ?? [])].reverse();
  for (const comment of comments) {
    if (!comment.authorLogin || !trusted.has(comment.authorLogin)) continue;
    const blockedBy = blockedByFromComment(comment.body);
    if (blockedBy.length > 0) return blockedBy;
  }
  return [];
}

export function replaceTriageStateLabels(
  labels: readonly string[],
  stateMap: PatchmillTriageStateMap,
  nextLabel: string,
): string[] {
  const triageStateLabels = new Set(Object.keys(stateMap));
  return [
    ...labels.filter((label) => !triageStateLabels.has(label)),
    nextLabel,
  ];
}

export function isClosedIssue(issue: Pick<IssueSummary, "state">): boolean {
  return issue.state.toLowerCase() === "closed";
}

export async function resolveBlockedIssue(
  host: BlockerHost,
  issue: Pick<IssueSummary, "comments" | "number">,
  trustedAuthors: readonly string[],
): Promise<BlockedIssueResolution> {
  const blockedBy = blockedByFromIssue(issue, trustedAuthors);
  if (blockedBy.length === 0) {
    return { status: "missing-blockers", blockedBy: [], openBlockers: [] };
  }
  if (blockedBy.length > MAX_BLOCKER_ISSUES) {
    throw new Error(
      `Blocked issue metadata for #${issue.number} lists ${blockedBy.length} blockers; maximum is ${MAX_BLOCKER_ISSUES}`,
    );
  }

  const blockerIssues: IssueSummary[] = [];
  for (const issueNumber of blockedBy) {
    blockerIssues.push(await host.viewIssue(issueNumber));
  }
  const openBlockers = blockerIssues
    .filter((blocker) => !isClosedIssue(blocker))
    .map((blocker) => blocker.number)
    .sort((left, right) => left - right);

  return openBlockers.length === 0
    ? { status: "unblocked", blockedBy, openBlockers }
    : { status: "still-blocked", blockedBy, openBlockers };
}
