import type { PatchmillTriageStateMap } from "../../../policy/triage-state.ts";
import type { IssueSummary } from "./types.ts";

export const TRIAGE_COMMENT_PREFIX =
  "> _This was generated by AI during triage._";

type BlockerHost = {
  viewIssue(issueNumber: number): Promise<IssueSummary>;
};

export type BlockedIssueResolution =
  | { status: "missing-blockers"; blockedBy: number[]; openBlockers: number[] }
  | { status: "still-blocked"; blockedBy: number[]; openBlockers: number[] }
  | { status: "unblocked"; blockedBy: number[]; openBlockers: number[] };

function issueRefs(issueNumbers: readonly number[]): string {
  return issueNumbers.map((issueNumber) => `#${issueNumber}`).join(", ");
}

function uniqueIssueNumbers(issueNumbers: readonly number[]): number[] {
  return [...new Set(issueNumbers)].sort((left, right) => left - right);
}

export function createBlockedComment(
  blockedBy: readonly number[],
  rationale: string,
): string {
  return [
    TRIAGE_COMMENT_PREFIX,
    "",
    `Blocked by: ${issueRefs(uniqueIssueNumbers(blockedBy))}`,
    "",
    rationale.trim(),
  ].join("\n");
}

export function createUnblockedComment(blockedBy: readonly number[]): string {
  return [
    TRIAGE_COMMENT_PREFIX,
    "",
    `The blocking issues are now closed: ${issueRefs(uniqueIssueNumbers(blockedBy))}.`,
    "",
    "This issue is now agent-ready.",
  ].join("\n");
}

function commentBody(comment: unknown): string | undefined {
  if (typeof comment === "string") return comment;
  if (comment && typeof comment === "object" && "body" in comment) {
    const body = (comment as Record<string, unknown>).body;
    if (typeof body === "string") return body;
  }
  return undefined;
}

function blockedByFromComment(comment: string): number[] {
  if (!comment.includes(TRIAGE_COMMENT_PREFIX)) return [];
  const blockedLine = comment
    .split(/\r?\n/u)
    .map((line) => line.trim())
    .find((line) => /^Blocked by:/iu.test(line));
  if (!blockedLine) return [];
  return uniqueIssueNumbers(
    [...blockedLine.matchAll(/#([1-9]\d*)/gu)].map((match) => Number(match[1])),
  );
}

export function blockedByFromIssue(
  issue: Pick<IssueSummary, "comments">,
): number[] {
  const comments = [...(issue.comments ?? [])].reverse();
  for (const comment of comments) {
    const body = commentBody(comment);
    if (!body) continue;
    const blockedBy = blockedByFromComment(body);
    if (blockedBy.length > 0) return blockedBy;
  }
  return [];
}

export function replaceTriageStateLabels(
  labels: readonly string[],
  stateMap: PatchmillTriageStateMap,
  nextLabel: string,
): string[] {
  const triageStateLabels = new Set(Object.keys(stateMap));
  return [
    ...labels.filter((label) => !triageStateLabels.has(label)),
    nextLabel,
  ];
}

export function isClosedIssue(issue: Pick<IssueSummary, "state">): boolean {
  return issue.state.toLowerCase() === "closed";
}

export async function resolveBlockedIssue(
  host: BlockerHost,
  issue: Pick<IssueSummary, "comments">,
): Promise<BlockedIssueResolution> {
  const blockedBy = blockedByFromIssue(issue);
  if (blockedBy.length === 0) {
    return { status: "missing-blockers", blockedBy: [], openBlockers: [] };
  }

  const blockerIssues = await Promise.all(
    blockedBy.map((issueNumber) => host.viewIssue(issueNumber)),
  );
  const openBlockers = blockerIssues
    .filter((blocker) => !isClosedIssue(blocker))
    .map((blocker) => blocker.number)
    .sort((left, right) => left - right);

  return openBlockers.length === 0
    ? { status: "unblocked", blockedBy, openBlockers }
    : { status: "still-blocked", blockedBy, openBlockers };
}
