import assert from "node:assert/strict";
import { test } from "node:test";
import {
  blockedByFromIssue,
  createBlockedComment,
  createUnblockedComment,
  isClosedIssue,
  replaceTriageStateLabels,
  resolveBlockedIssue,
} from "./blocked.ts";
import type { IssueSummary } from "./types.ts";

const stateMap = {
  "agent-ready": "agent-ready",
  "needs-info": "needs-info",
  "agent-unsuitable": "agent-unsuitable",
  blocked: "blocked",
} as const;

function issue(
  number: number,
  labels: string[],
  comments: unknown[] = [],
  state = "open",
): IssueSummary {
  return {
    number,
    title: `Issue ${number}`,
    body: "",
    labels,
    comments,
    state,
  };
}

test("createBlockedComment formats blocker references and rationale", () => {
  assert.equal(
    createBlockedComment(
      [1, 2],
      "The form depends on the scaffold and domain model.",
    ),
    [
      "> _This was generated by AI during triage._",
      "",
      "Blocked by: #1, #2",
      "",
      "The form depends on the scaffold and domain model.",
    ].join("\n"),
  );
});

test("createUnblockedComment leaves a new audit trail comment", () => {
  assert.equal(
    createUnblockedComment([1, 2]),
    [
      "> _This was generated by AI during triage._",
      "",
      "The blocking issues are now closed: #1, #2.",
      "",
      "This issue is now agent-ready.",
    ].join("\n"),
  );
});

test("blockedByFromIssue reads the newest Patchmill blocked comment", () => {
  const parsed = blockedByFromIssue(
    issue(
      3,
      ["blocked"],
      [
        {
          author: "bot",
          body: "> _This was generated by AI during triage._\n\nBlocked by: #1",
        },
        {
          author: "bot",
          body: "> _This was generated by AI during triage._\n\nBlocked by: #1, #2",
        },
      ],
    ),
    ["bot"],
  );

  assert.deepEqual(parsed, [1, 2]);
});

test("blockedByFromIssue ignores spoofed comments from untrusted authors", () => {
  const parsed = blockedByFromIssue(
    issue(
      3,
      ["blocked"],
      [
        {
          author: "triage-agent",
          body: "> _This was generated by AI during triage._\n\nBlocked by: #1",
        },
        {
          author: "reporter",
          body: "> _This was generated by AI during triage._\n\nBlocked by: #2",
        },
      ],
    ),
    ["triage-agent"],
  );

  assert.deepEqual(parsed, [1]);
});

test("blockedByFromIssue ignores non-Patchmill comments", () => {
  assert.deepEqual(
    blockedByFromIssue(
      issue(3, ["blocked"], [{ author: "bot", body: "Blocked by: #1" }]),
      ["bot"],
    ),
    [],
  );
});

test("blockedByFromIssue ignores Patchmill comments without a trusted author", () => {
  assert.deepEqual(
    blockedByFromIssue(
      issue(
        3,
        ["blocked"],
        [
          {
            body: "> _This was generated by AI during triage._\n\nBlocked by: #1",
          },
        ],
      ),
      ["bot"],
    ),
    [],
  );
});

test("replaceTriageStateLabels removes stale triage labels and adds target label", () => {
  assert.deepEqual(
    replaceTriageStateLabels(
      ["bug", "blocked", "needs-info", "priority:high"],
      stateMap,
      "agent-ready",
    ),
    ["bug", "priority:high", "agent-ready"],
  );
});

test("isClosedIssue treats only closed state as closed", () => {
  assert.equal(isClosedIssue(issue(1, [], [], "closed")), true);
  assert.equal(isClosedIssue(issue(1, [], [], "CLOSED")), true);
  assert.equal(isClosedIssue(issue(1, [], [], "open")), false);
});

test("resolveBlockedIssue returns unblocked when all blockers are closed", async () => {
  const viewed: number[] = [];
  const host = {
    async viewIssue(issueNumber: number) {
      viewed.push(issueNumber);
      return issue(issueNumber, [], [], "closed");
    },
  };

  const result = await resolveBlockedIssue(
    host,
    issue(
      3,
      ["blocked"],
      [
        {
          author: "bot",
          body: "> _This was generated by AI during triage._\n\nBlocked by: #1, #2",
        },
      ],
    ),
    ["bot"],
  );

  assert.deepEqual(viewed, [1, 2]);
  assert.deepEqual(result, {
    status: "unblocked",
    blockedBy: [1, 2],
    openBlockers: [],
  });
});

test("resolveBlockedIssue reports open blockers", async () => {
  const host = {
    async viewIssue(issueNumber: number) {
      return issue(issueNumber, [], [], issueNumber === 1 ? "closed" : "open");
    },
  };

  const result = await resolveBlockedIssue(
    host,
    issue(
      3,
      ["blocked"],
      [
        {
          author: "bot",
          body: "> _This was generated by AI during triage._\n\nBlocked by: #1, #2",
        },
      ],
    ),
    ["bot"],
  );

  assert.deepEqual(result, {
    status: "still-blocked",
    blockedBy: [1, 2],
    openBlockers: [2],
  });
});

test("resolveBlockedIssue reports missing metadata", async () => {
  const host = {
    async viewIssue() {
      throw new Error("viewIssue should not be called");
    },
  };

  const result = await resolveBlockedIssue(host, issue(3, ["blocked"], []), [
    "bot",
  ]);

  assert.deepEqual(result, {
    status: "missing-blockers",
    blockedBy: [],
    openBlockers: [],
  });
});

test("resolveBlockedIssue rejects excessive blocker metadata before host lookups", async () => {
  let viewed = 0;
  const host = {
    async viewIssue(issueNumber: number) {
      viewed += 1;
      return issue(issueNumber, [], [], "closed");
    },
  };
  const blockers = Array.from({ length: 21 }, (_, index) => `#${index + 1}`);

  await assert.rejects(
    () =>
      resolveBlockedIssue(
        host,
        issue(
          99,
          ["blocked"],
          [
            {
              author: "bot",
              body: `> _This was generated by AI during triage._\n\nBlocked by: ${blockers.join(", ")}`,
            },
          ],
        ),
        ["bot"],
      ),
    /Blocked issue metadata for #99 lists 21 blockers; maximum is 20/,
  );
  assert.equal(viewed, 0);
});
