import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { DEFAULT_PATCHMILL_CONFIG } from "../../../config/defaults.ts";
import { createStaticCommandRunner } from "../../../../test-support/command-runner.ts";
import { runTriage } from "./pipeline.ts";

function previewJson(previews: unknown[]): string {
  return JSON.stringify({ previews });
}

const forgejoTrustedAuthorOutput = {
  code: 0,
  stdout: JSON.stringify([
    { name: "triage-agent", user: "triage-agent", default: "true" },
  ]),
  stderr: "",
};

test("runTriage dry-run trusts active GitHub user for blocked metadata when config login is empty", async () => {
  const logDir = await mkdtemp(join(tmpdir(), "triage-pipeline-blocked-"));
  const calls: Array<{ command: string; args: string[]; cwd?: string }> = [];
  const runner = {
    calls,
    async run(command: string, args: string[], options = {}) {
      calls.push({ command, args: [...args], cwd: options.cwd });

      if (command === "gh" && args.slice(0, 2).join(" ") === "issue list") {
        return {
          code: 0,
          stdout: JSON.stringify([
            {
              number: 3,
              title: "Create poll form",
              body: "Blocked by scaffold and model.",
              state: "OPEN",
              labels: [{ name: "blocked" }, { name: "enhancement" }],
            },
          ]),
          stderr: "",
        };
      }

      if (command === "gh" && args.join(" ") === "api user --jq .login") {
        return { code: 0, stdout: "triage-agent\n", stderr: "" };
      }

      if (command === "gh" && args.slice(0, 3).join(" ") === "issue view 3") {
        return {
          code: 0,
          stdout: JSON.stringify({
            number: 3,
            title: "Create poll form",
            body: "Blocked by scaffold and model.",
            state: "OPEN",
            labels: [{ name: "blocked" }, { name: "enhancement" }],
            comments: [
              {
                author: { login: "triage-agent" },
                body: "> _This was generated by AI during triage._\n\nBlocked by: #1, #2",
              },
            ],
          }),
          stderr: "",
        };
      }

      if (command === "gh" && args.slice(0, 3).join(" ") === "issue view 1") {
        return {
          code: 0,
          stdout: JSON.stringify({
            number: 1,
            title: "Scaffold",
            body: "Done",
            state: "CLOSED",
            labels: [],
            comments: [],
          }),
          stderr: "",
        };
      }

      if (command === "gh" && args.slice(0, 3).join(" ") === "issue view 2") {
        return {
          code: 0,
          stdout: JSON.stringify({
            number: 2,
            title: "Model",
            body: "Done",
            state: "CLOSED",
            labels: [],
            comments: [],
          }),
          stderr: "",
        };
      }

      if (command === "pi") {
        return {
          code: 0,
          stdout: previewJson([
            {
              issueNumber: 3,
              currentLabels: ["blocked", "enhancement"],
              proposedLabels: ["enhancement", "agent-ready"],
              canonicalBucket: "agent-ready",
              rationale:
                "Agent fallback should not handle trusted blocked metadata.",
              wouldComment: null,
              wouldClose: false,
              questions: [],
            },
          ]),
          stderr: "",
        };
      }

      throw new Error(`Unexpected command: ${command} ${args.join(" ")}`);
    },
  };

  const result = await runTriage(runner, {
    repoRoot: "/repo",
    dryRun: true,
    execute: false,
    logDir,
    host: { provider: "github-gh", login: "" },
  });

  assert.equal(result.status, "dry-run");
  assert.equal(result.issues[0]?.primaryBucket, "agent-ready");
  assert.deepEqual(result.issues[0]?.blockedBy, [1, 2]);
  assert.equal(
    calls.some(
      (call) =>
        call.command === "gh" && call.args.join(" ") === "api user --jq .login",
    ),
    true,
  );
  assert.equal(
    calls.some((call) => call.command === "pi"),
    false,
  );
});

test("runTriage dry-run previews blocked issue auto-unblock when Forgejo blockers are closed", async () => {
  const logDir = await mkdtemp(join(tmpdir(), "triage-pipeline-blocked-"));
  const runner = createStaticCommandRunner([
    {
      code: 0,
      stdout: JSON.stringify([
        {
          index: 3,
          title: "Create poll form",
          body: "Blocked by scaffold and model.",
          state: "open",
          labels: [{ name: "blocked" }, { name: "enhancement" }],
        },
      ]),
      stderr: "",
    },
    { code: 0, stdout: JSON.stringify([]), stderr: "" },
    {
      code: 0,
      stdout:
        "## Comments\n**@triage-agent** wrote on 2026-05-25 12:00:\n> _This was generated by AI during triage._\n\nBlocked by: #1, #2\n\nWaiting on prerequisites.\n--------\n",
      stderr: "",
    },
    forgejoTrustedAuthorOutput,
    {
      code: 0,
      stdout: JSON.stringify([
        {
          index: 1,
          title: "Scaffold",
          body: "Done",
          state: "closed",
          labels: [],
          comments: [],
        },
      ]),
      stderr: "",
    },
    {
      code: 0,
      stdout: JSON.stringify([
        {
          index: 2,
          title: "Model",
          body: "Done",
          state: "closed",
          labels: [],
          comments: [],
        },
      ]),
      stderr: "",
    },
  ]);

  const result = await runTriage(runner, {
    repoRoot: "/repo",
    dryRun: true,
    execute: false,
    logDir,
    host: DEFAULT_PATCHMILL_CONFIG.host,
  });

  assert.equal(result.status, "dry-run");
  assert.deepEqual(result.issues[0], {
    issueNumber: 3,
    title: "Create poll form",
    previousLabels: ["blocked", "enhancement"],
    finalLabels: ["enhancement", "agent-ready"],
    primaryBucket: "agent-ready",
    blockedBy: [1, 2],
    rationale: "All blocking issues are closed: #1, #2.",
    questions: [],
    comment: [
      "> _This was generated by AI during triage._",
      "",
      "The blocking issues are now closed: #1, #2.",
      "",
      "This issue is now agent-ready.",
    ].join("\n"),
    wouldClose: false,
    mutationStatus: "preview",
  });
  assert.equal(
    runner.calls.some(
      (call) =>
        call.command === "tea" &&
        call.args.join(" ") === "logins list --output json",
    ),
    true,
  );
  assert.equal(
    runner.calls.some((call) => call.command === "pi"),
    false,
  );
});

test("runTriage execute removes blocked and adds agent-ready when blockers are closed", async () => {
  const logDir = await mkdtemp(join(tmpdir(), "triage-pipeline-blocked-"));
  const runner = {
    calls: [] as Array<{ command: string; args: string[]; cwd?: string }>,
    async run(command: string, args: string[], options = {}) {
      runner.calls.push({ command, args: [...args], cwd: options.cwd });

      if (command === "gh" && args.slice(0, 2).join(" ") === "issue list") {
        return {
          code: 0,
          stdout: JSON.stringify([
            {
              number: 3,
              title: "Create poll form",
              body: "Blocked by scaffold and model.",
              state: "OPEN",
              labels: [{ name: "blocked" }, { name: "enhancement" }],
              url: "https://example.test/issues/3",
            },
          ]),
          stderr: "",
        };
      }

      if (command === "gh" && args.join(" ") === "api user --jq .login") {
        return { code: 0, stdout: "triage-agent\n", stderr: "" };
      }

      if (command === "gh" && args.slice(0, 3).join(" ") === "issue view 3") {
        const edited = runner.calls.some(
          (call) =>
            call.command === "gh" &&
            call.args.slice(0, 3).join(" ") === "issue edit 3",
        );
        const commented = runner.calls.some(
          (call) =>
            call.command === "gh" &&
            call.args.slice(0, 3).join(" ") === "issue comment 3",
        );
        return {
          code: 0,
          stdout: JSON.stringify({
            number: 3,
            title: "Create poll form",
            body: "Blocked by scaffold and model.",
            state: "OPEN",
            labels: edited
              ? [{ name: "agent-ready" }, { name: "enhancement" }]
              : [{ name: "blocked" }, { name: "enhancement" }],
            url: "https://example.test/issues/3",
            comments: commented
              ? [
                  {
                    author: { login: "triage-agent" },
                    body: "> _This was generated by AI during triage._\n\nBlocked by: #1, #2",
                  },
                  {
                    author: { login: "triage-agent" },
                    body: "> _This was generated by AI during triage._\n\nThe blocking issues are now closed: #1, #2.\n\nThis issue is now agent-ready.",
                  },
                ]
              : [
                  {
                    author: { login: "triage-agent" },
                    body: "> _This was generated by AI during triage._\n\nBlocked by: #1, #2",
                  },
                ],
          }),
          stderr: "",
        };
      }

      if (command === "gh" && args.slice(0, 3).join(" ") === "issue view 1") {
        return {
          code: 0,
          stdout: JSON.stringify({
            number: 1,
            title: "Scaffold",
            body: "Done",
            state: "CLOSED",
            labels: [],
            comments: [],
          }),
          stderr: "",
        };
      }

      if (command === "gh" && args.slice(0, 3).join(" ") === "issue view 2") {
        return {
          code: 0,
          stdout: JSON.stringify({
            number: 2,
            title: "Model",
            body: "Done",
            state: "CLOSED",
            labels: [],
            comments: [],
          }),
          stderr: "",
        };
      }

      if (command === "gh" && args.slice(0, 3).join(" ") === "issue edit 3") {
        assert.ok(args.includes("--add-label"));
        assert.ok(args.includes("agent-ready"));
        assert.ok(args.includes("--remove-label"));
        assert.ok(args.includes("blocked"));
        return { code: 0, stdout: "", stderr: "" };
      }

      if (
        command === "gh" &&
        args.slice(0, 3).join(" ") === "issue comment 3"
      ) {
        assert.match(
          args.join(" "),
          /The blocking issues are now closed: #1, #2\./,
        );
        return { code: 0, stdout: "", stderr: "" };
      }

      throw new Error(`Unexpected command: ${command} ${args.join(" ")}`);
    },
  };

  const result = await runTriage(runner, {
    repoRoot: "/repo",
    dryRun: false,
    execute: true,
    logDir,
    host: { provider: "github-gh", login: "" },
  });

  assert.equal(result.status, "applied");
  assert.equal(result.issues[0]?.primaryBucket, "agent-ready");
  assert.deepEqual(result.issues[0]?.blockedBy, [1, 2]);
  assert.equal(result.issues[0]?.comment?.includes("now closed"), true);
  assert.equal(
    runner.calls.some(
      (call) =>
        call.command === "gh" && call.args.join(" ") === "api user --jq .login",
    ),
    true,
  );
  assert.equal(
    runner.calls.some((call) => call.command === "pi"),
    false,
  );
});
