import assert from "node:assert/strict";
import { test } from "node:test";
import {
  createObservedChangeEntries,
  createPreviewEntries,
  extractNeedsInfoFollowUps,
} from "./reporting.ts";
import type { IssueSummary, TriagePreview } from "./types.ts";

const stateMap = {
  "ready-for-agent": "agent-ready",
  "needs-info": "needs-info",
  "ready-for-human": "agent-unsuitable",
  blocked: "blocked",
  wontfix: "agent-unsuitable",
} as const;

function issue(
  number: number,
  labels: string[],
  comments: unknown[] = [],
  state = "open",
  url?: string,
): IssueSummary {
  return {
    number,
    title: `Issue ${number}`,
    body: "",
    labels,
    state,
    comments,
    ...(url ? { url } : {}),
  };
}

test("createPreviewEntries converts dry-run previews into log entries", () => {
  const previews: TriagePreview[] = [
    {
      issueNumber: 1,
      currentLabels: ["stale-model-label"],
      proposedLabels: ["ready-for-agent", "bug"],
      canonicalBucket: "agent-ready",
      blockedBy: [],
      rationale: "Clear enough.",
      wouldComment: "## Agent Brief\nImplement it.",
      wouldClose: false,
      questions: [],
    },
  ];

  assert.deepEqual(
    createPreviewEntries([issue(1, ["needs-triage", "bug"])], previews),
    [
      {
        issueNumber: 1,
        title: "Issue 1",
        previousLabels: ["needs-triage", "bug"],
        finalLabels: ["ready-for-agent", "bug"],
        primaryBucket: "agent-ready",
        rationale: "Clear enough.",
        questions: [],
        comment: "## Agent Brief\nImplement it.",
        wouldClose: false,
        mutationStatus: "preview",
      },
    ],
  );
});

test("createPreviewEntries includes issue URL when available", () => {
  const previews: TriagePreview[] = [
    {
      issueNumber: 1,
      currentLabels: ["bug"],
      proposedLabels: ["agent-ready", "bug"],
      canonicalBucket: "agent-ready",
      blockedBy: [],
      rationale: "Clear enough.",
      wouldComment: null,
      wouldClose: false,
      questions: [],
    },
  ];

  const entries = createPreviewEntries(
    [issue(1, ["bug"], [], "open", "https://example.test/issues/1")],
    previews,
  );

  assert.equal(entries[0]?.url, "https://example.test/issues/1");
});

test("createPreviewEntries carries blockedBy into blocked log entries", () => {
  const previews: TriagePreview[] = [
    {
      issueNumber: 1,
      currentLabels: ["bug"],
      proposedLabels: ["blocked", "bug"],
      canonicalBucket: "blocked",
      blockedBy: [2, 3],
      rationale: "Blocked by prerequisite issues.",
      wouldComment:
        "> _This was generated by AI during triage._\n\nBlocked by: #2, #3",
      wouldClose: false,
      questions: [],
    },
  ];

  assert.deepEqual(createPreviewEntries([issue(1, ["bug"])], previews), [
    {
      issueNumber: 1,
      title: "Issue 1",
      previousLabels: ["bug"],
      finalLabels: ["blocked", "bug"],
      primaryBucket: "blocked",
      blockedBy: [2, 3],
      rationale: "Blocked by prerequisite issues.",
      questions: [],
      comment:
        "> _This was generated by AI during triage._\n\nBlocked by: #2, #3",
      wouldClose: false,
      mutationStatus: "preview",
    },
  ]);
});

test("createObservedChangeEntries reports labels, comments, state, and bucket", () => {
  const before = [
    issue(1, ["needs-triage", "bug"], [{ author: "bot", body: "old comment" }]),
  ];
  const after = [
    issue(
      1,
      ["ready-for-agent", "bug"],
      [
        { author: "bot", body: "old comment" },
        { author: "bot", body: "## Agent Brief\nImplement CSV export." },
      ],
      "open",
    ),
  ];

  assert.deepEqual(createObservedChangeEntries(before, after, stateMap), [
    {
      issueNumber: 1,
      title: "Issue 1",
      previousLabels: ["needs-triage", "bug"],
      finalLabels: ["ready-for-agent", "bug"],
      primaryBucket: "agent-ready",
      questions: [],
      comment: "## Agent Brief\nImplement CSV export.",
      addedComments: ["## Agent Brief\nImplement CSV export."],
      previousState: "open",
      finalState: "open",
      mutationStatus: "observed",
    },
  ]);
});

test("createObservedChangeEntries includes after snapshot URL", () => {
  const entries = createObservedChangeEntries(
    [issue(1, ["needs-triage"], [], "open", "https://old.test/1")],
    [issue(1, ["agent-ready"], [], "open", "https://new.test/1")],
    stateMap,
  );

  assert.equal(entries[0]?.url, "https://new.test/1");
});

test("createObservedChangeEntries extracts blockedBy from Patchmill blocked comments", () => {
  const before = [issue(3, ["bug"], [])];
  const blockedComment =
    "> _This was generated by AI during triage._\n\nBlocked by: #1, #2\n\nWaiting for prerequisites.";
  const after = [issue(3, ["blocked", "bug"], [{ body: blockedComment }])];

  assert.deepEqual(createObservedChangeEntries(before, after, stateMap), [
    {
      issueNumber: 3,
      title: "Issue 3",
      previousLabels: ["bug"],
      finalLabels: ["blocked", "bug"],
      primaryBucket: "blocked",
      blockedBy: [1, 2],
      questions: [],
      comment: blockedComment,
      addedComments: [blockedComment],
      previousState: "open",
      finalState: "open",
      mutationStatus: "observed",
    },
  ]);
});

test("createObservedChangeEntries throws when an after snapshot is missing", () => {
  assert.throws(
    () =>
      createObservedChangeEntries(
        [issue(1, ["needs-triage"])],
        [issue(2, ["ready-for-agent"])],
        stateMap,
      ),
    /Missing after snapshot for issue #1/,
  );
});

test("extractNeedsInfoFollowUps returns question-like lines", () => {
  assert.deepEqual(
    extractNeedsInfoFollowUps(
      "## Triage Notes\n\n- What browser fails?\n- Please share logs\nPlain sentence",
    ),
    ["What browser fails?", "Please share logs"],
  );
});

test("extractNeedsInfoFollowUps strips ordered markdown list markers", () => {
  assert.deepEqual(
    extractNeedsInfoFollowUps(
      "## Need more info\n\n1. What browser fails?\n2) Please share logs\n3. Attach a screenshot\nPlain sentence",
    ),
    ["What browser fails?", "Please share logs", "Attach a screenshot"],
  );
});

test("extractNeedsInfoFollowUps falls back to full comment", () => {
  assert.deepEqual(extractNeedsInfoFollowUps("Need reporter details."), [
    "Need reporter details.",
  ]);
});
