import type { PatchmillProjectPolicy } from "./types.ts";

const CROPRUN_COMPAT_DIRECT_LAND_POLICY = [
  "Landing policy:",
  "Default to direct squash-landing on `<target-branch>` when the completed change is safe for asynchronous human QA on staging. Only create a PR when human code review is required before landing.",
  "",
  "Direct squash-land eligibility — all must be true:",
  "- The issue is a simple bug fix or mechanical change.",
  "- The implementation exactly matches the issue and plan; no opportunistic refactor or extra behavior change.",
  "- The final diff is localized and easy to review after the fact.",
  "- All required validation from AGENTS.md passed using the approved commands.",
  "- A fresh reviewer agent reviewed the final diff and found no unresolved concerns.",
  "- Visual UI changes require fresh screenshots and reviewer screenshot approval before direct squash-land.",
  "- The branch contains only commits from this automation run.",
  "- You can update `<target-branch>`, squash the branch cleanly, and push without force-pushing.",
  "",
  "Simple bug fix means:",
  "- The incorrect behavior and intended behavior are clear.",
  "- The fix is narrowly scoped.",
  "- Regression coverage was added or updated when practical.",
  "- No product, UX, architecture, schema, compatibility, security, or release decision is required.",
  "",
  "Mechanical change means:",
  "- The change is deterministic and repetitive.",
  "- Runtime behavior is unchanged, unless the issue explicitly requests the behavior change.",
  "- Examples: typo fixes, formatting, import cleanup, generated snapshot updates, straightforward renames, small test expectation updates caused by an intentional nearby change.",
  "",
  "Human-review-required exclusions — create a PR instead of landing directly if any are true:",
  "- Database migrations, schema changes, or persistent data-format changes.",
  "- Auth, security, privacy, permissions, secrets, billing, or data-loss risk.",
  "- Public API, mobile/server contract, offline sync, conflict resolution, scanner/camera, or device/instrumentation behavior.",
  "- Dependency, Nix, CI, deployment, release, or infrastructure changes.",
  "- Broad refactors, large diffs, or changes spanning unrelated areas.",
  "- Any validation was skipped, failed, flaky, unavailable, or substituted.",
  "- Reviewer raised unresolved concerns.",
  "- You are uncertain whether direct landing is appropriate.",
  "",
  "If eligible for direct squash-land:",
  "1. Do not create a PR.",
  "2. Update local `<target-branch>` from the `<remote>` remote.",
  "3. Squash-merge the implementation branch into `<target-branch>`.",
  "4. Create one Conventional Commit that references issue #<n>.",
  "5. Push `<target-branch>` to `<remote>` without force-pushing.",
  "6. Do not create a PR or post the issue handoff comment yourself; the runner will comment after it parses the final response.",
  "7. Return the `merged` final response.",
  "",
  "If human review is required:",
  "1. Push the branch to `<remote>` and open a Forgejo PR with `tea`.",
  "2. Explain briefly why human review is required.",
  "3. Return the `pr-created` final response.",
  "",
  "Blocker contract:",
  "If human input is required, stop safely, leave committed work as-is, keep the reason and questions concise enough to post directly as a `needs-info` comment, and return this exact JSON object as the final response:",
  "{",
  '  "status": "blocked",',
  '  "reason": "short reason",',
  '  "questions": [',
  "    {",
  '      "question": "question a human must answer",',
  '      "recommendedAnswer": "recommended answer and reasoning"',
  "    }",
  "  ],",
  '  "commits": ["<sha>"],',
  '  "validation": ["command and result summary"]',
  "}",
  "",
  "Successful final response for direct squash-land:",
  "Return this exact JSON object after `<target-branch>` is pushed successfully:",
  "{",
  '  "status": "merged",',
  '  "branch": "<implementation-branch>",',
  '  "mergeCommit": "<squash commit sha on <target-branch>>",',
  '  "commits": ["<implementation commit sha>"],',
  '  "validation": ["command and result summary"],',
  '  "reviewSummary": "short reviewer/fix summary",',
  '  "landingDecision": "direct squash-landed: simple localized bug fix"',
  "}",
  "",
  "Successful final response for human-review PR fallback:",
  "Return this exact JSON object after PR handoff succeeds:",
  "{",
  '  "status": "pr-created",',
  '  "prUrl": "<Forgejo PR URL>",',
  '  "branch": "<implementation-branch>",',
  '  "commits": ["<sha>"],',
  '  "validation": ["command and result summary"],',
  '  "visualEvidence": [',
  "    {",
  '      "screenshotPath": ".tmp/issue-42-dashboard-after.png",',
  '      "caption": "Dashboard after selecting last 8 weeks",',
  '      "referencePaths": ["docs/reference-screenshots/web/01-dashboard.png"]',
  "    }",
  "  ],",
  '  "reviewSummary": "short reviewer/fix summary",',
  '  "landingDecision": "PR required: <reason>"',
  "}",
].join("\n");

const CROPRUN_COMPAT_VISUAL_EVIDENCE_POLICY = [
  "Visual-change evidence:",
  "- For new screens without a direct before state, compare against adjacent or analogous reference screenshots from the same app area.",
  "- Capture fresh after-change screenshots after implementation and required validation.",
  "- Record after-change screenshot paths, relevant reference screenshot paths, and what each screenshot proves in `validation`.",
  "- Return structured `visualEvidence` entries for PR fallback so the orchestrator can upload screenshots to the Forgejo PR.",
  "- Do not upload visual evidence to Forgejo yourself; the orchestrator handles the upload after parsing your final JSON.",
  "- A worktree-local screenshot path alone is not sufficient PR evidence; include it in `visualEvidence` so it can be uploaded.",
  "- If required screenshots cannot be captured, do not direct-land; return blocked or create a PR with the exact reason.",
].join("\n");

const CROPRUN_COMPAT_PI_TODO_WORKFLOW_INSTRUCTION = [
  "Plan-creation todo workflow:",
  "- Create or update todos using the Pi `todo` tool for each implementation plan task.",
  "- Use one todo per actionable plan task.",
  "- Do not represent all implementation work as one todo.",
  "- Use the naming convention `issue-<n>-task-<two-digit-number>-<slug>`.",
  "- Tag each task todo with `agent-issue` and `issue-<n>`.",
  "- Do not commit `.pi/todos` or todo files; they are local operator state.",
  "- Each task todo body must include: purpose, the source plan checklist item, checkpoint details, and any last error or validation notes known at planning time.",
  "- After the plan document is committed, mark the plan-related task todos complete so they reflect the committed plan state.",
  "",
  "Implementation todo workflow:",
  "- Use the Pi `todo` tool to manage this issue.",
  "- Read existing todos tagged `agent-issue` and `issue-<n>` before starting implementation work.",
  "- Create one todo for each actionable task in the implementation plan.",
  "- Create or update missing per-plan-task todos using the naming convention `issue-<n>-task-<two-digit-number>-<slug>`.",
  "- Tag each task todo with `agent-issue` and `issue-<n>`.",
  "- Do not commit `.pi/todos` or todo files; they are local operator state.",
  "- Each task todo body must include: purpose, the source plan checklist item, checkpoint details, and the latest last error or validation notes.",
  "- Do not create a single broad implementation todo.",
  "- Claim or update the current task todo before doing work on that task.",
  "- Mark a task todo complete only after code, tests, review, fixes, and verification for that task are done.",
  "- Complete every `issue-<n>-task-*` todo before creating a PR, merging, or returning final JSON.",
  "- The orchestrator rejects `pr-created` or `merged` results while any issue task todo remains open.",
  "- Keep review tracking and final handoff tracking separate from implementation task todos.",
].join("\n");

export const CROPRUN_COMPAT_POLICY: PatchmillProjectPolicy = {
  projectName: "Croprun",
  contextFileNames: ["AGENTS.md"],
  toolchainInstruction:
    "Use the devenv-managed project toolchain. If the shell is not already active, enter it with `devenv shell` or prefix one-off commands with `devenv shell <command>`.",
  validation: {
    rules: [
      { category: "Server-side changes", commands: ["just test"] },
      { category: "Playwright/browser flows", commands: ["just playwright-test"] },
      { category: "Mobile unit changes", commands: ["just mobile-test"] },
      { category: "Android instrumentation/device behavior", commands: ["just mobile-instrumentation-test"] },
    ],
    forbiddenSubstitutions: [
      "Do not run host `go test` as a substitute.",
      "Do not run host `playwright test` as a substitute.",
      "Do not use ad-hoc servers as a substitute.",
      "Do not run direct `kubectl exec` as a substitute.",
    ],
  },
  directLand: {
    targetBranch: "main",
    policyText: CROPRUN_COMPAT_DIRECT_LAND_POLICY,
  },
  visualEvidence: {
    policyText: CROPRUN_COMPAT_VISUAL_EVIDENCE_POLICY,
    webScreenshotSkill: "capturing-proof-screenshots",
    mobileScreenshotSkill: "mobile-app-screenshots",
    referenceScreenshotPaths: ["docs/reference-screenshots/web/", "docs/reference-screenshots/mobile/"],
    reviewerExpectations: [
      "If visuals intentionally change, update the relevant committed reference screenshots as part of the change.",
      "Ask the fresh reviewer to compare after-change screenshots against the issue requirements, relevant reference screenshots, and existing Croprun styling.",
      "The reviewer summary must state whether screenshot review passed when visual changes exist.",
    ],
    prEvidenceExample: {
      screenshotPath: ".tmp/issue-42-dashboard-after.png",
      caption: "Dashboard after selecting last 8 weeks",
      referencePaths: ["docs/reference-screenshots/web/01-dashboard.png"],
    },
  },
  hostToolingInstruction: "Use Forgejo `tea` for repository-hosting actions. Do not use `gh`.",
  pi: {
    todoWorkflowInstruction: CROPRUN_COMPAT_PI_TODO_WORKFLOW_INSTRUCTION,
    subagentWorkflowInstruction: [
      "Use `superpowers:subagent-driven-development` to execute the plan task by task. Do not substitute an ad-hoc implementation loop for this skill.",
      "Before dispatching implementation or review subagents, use `superpowers:selecting-subagent-models` and apply the authoritative agent team mappings.",
      "Use fresh reviewer agents for each review pass and follow the skill's required worker/reviewer/checkpoint workflow, including its TDD, verification, review, and fix/re-verify expectations.",
    ].join("\n"),
  },
  planRequiresApproval: false,
};

export const DEFAULT_PATCHMILL_POLICY: PatchmillProjectPolicy = {
  contextFileNames: ["AGENTS.md"],
  toolchainInstruction: "Use the repository's documented development toolchain.",
  validation: {
    rules: [],
    forbiddenSubstitutions: [],
  },
  directLand: {
    targetBranch: "main",
    policyText: "Apply the repository's configured landing policy for the target branch.",
  },
  visualEvidence: {
    policyText: "Capture the visual evidence required by the repository whenever visible UI changes.",
    prEvidenceExample: {
      screenshotPath: ".tmp/issue-42-after.png",
      caption: "Visible UI state after the change",
    },
  },
  hostToolingInstruction: "Use the repository's configured host tooling for issue and pull-request actions.",
  pi: {
    todoWorkflowInstruction:
      "Use the Pi `todo` tool to track plan and implementation tasks. Do not commit `.pi/todos` or todo files.",
    subagentWorkflowInstruction:
      "Use the repository's documented Pi subagent workflow for implementation and review.",
  },
  planRequiresApproval: false,
};
